myapp.lo: /home/duythien/git/myapp/ext/myapp.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/myapp.c -o myapp.lo 
kernel/main.lo: /home/duythien/git/myapp/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/duythien/git/myapp/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/duythien/git/myapp/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /home/duythien/git/myapp/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /home/duythien/git/myapp/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/duythien/git/myapp/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/duythien/git/myapp/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/duythien/git/myapp/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /home/duythien/git/myapp/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /home/duythien/git/myapp/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/duythien/git/myapp/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /home/duythien/git/myapp/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/duythien/git/myapp/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/duythien/git/myapp/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /home/duythien/git/myapp/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/duythien/git/myapp/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /home/duythien/git/myapp/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/kernel/filter.c -o kernel/filter.lo 
myapp/normalizechars.lo: /home/duythien/git/myapp/ext/myapp/normalizechars.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/myapp/normalizechars.c -o myapp/normalizechars.lo 
myapp/quantum.lo: /home/duythien/git/myapp/ext/myapp/quantum.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/duythien/git/myapp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/duythien/git/myapp/ext/myapp/quantum.c -o myapp/quantum.lo 
$(phplibdir)/myapp.la: ./myapp.la
	$(LIBTOOL) --mode=install cp ./myapp.la $(phplibdir)

./myapp.la: $(shared_objects_myapp) $(MYAPP_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_myapp) $(MYAPP_SHARED_LIBADD)

